FinalProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('zomato.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zomato/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('create-reservation/', views.inputs, name='create_reservation'),
    path('', views.homepage, name='homepage'),
    path('hotel/<int:hotel_id>/', views.hotel_detail, name='hotel_detail'),
    path('create-reservation/reservation-success', views.reservation_success, name='reservation-success'),


]   

zomato/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxLengthValidator

# Create your models here.

class Hotel(models.Model):
  name = models.CharField(max_length = 100)
  address = models.CharField(max_length = 200)
  pool =  models.BooleanField() # True if hotel has a swimming pool, False otherwise
  gym = models.BooleanField(default = False)    # True if hotel has a gym, False otherwise
  rating_choices = [
    (1, '1 star'),
    (2, '2 stars'),
    (3, '3 stars'),
    (4, '4 stars'),
    (5, '5 stars'),
  ]

  rating = models.IntegerField(choices=rating_choices)
 # Rating of the hotel on a scale of 1 to 5
  
  logo = models.ImageField(upload_to='hotel_images/', blank=True, null=True)
  image_1 = models.ImageField(upload_to='hotel_images/', blank=True, null=True)
  image_2 = models.ImageField(upload_to='hotel_images/', blank=True, null=True)
  image_3 = models.ImageField(upload_to='hotel_images/', blank=True, null=True)
  image_4 = models.ImageField(upload_to='hotel_images/', blank=True, null=True)

  
  def __str__(self):
    return self.name + " ("+ str(self.rating)+" stars)"
  
class RoomType(models.Model):
  type = models.CharField(max_length=5) # Type of room
  description = models.TextField()
  hotels = models.ManyToManyField(Hotel , related_name= 'roomtypes') # Related field name is by default `hotels`

  def __str__(self):
    return self.type

class Room(models.Model):
    room_number = models.IntegerField(
       validators = [
          MinLengthValidator(3),
          MaxLengthValidator(3)
       ]
    )
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE, related_name='rooms')

    def __str__(self):
        return f"Room {self.room_number} ({self.room_type})"

class Reservation(models.Model):
    name = models.CharField(max_length = 100, default = None)
    phone  = models.IntegerField(default = None)
    email = models.EmailField(default = None)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    check_in_date = models.DateField()
    check_out_date = models.DateField()

    def __str__(self):
        return f"{self.name}'s reservation of {self.room} at {self.hotel}"

zomato/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Hotel, RoomType, Reservation

def inputs(request):
   
    # Handle the case when the form is not submitted or incomplete
    hotels = Hotel.objects.all()
    room_types = RoomType.objects.all()
    context = {
        'hotels': hotels,
        'room_types': room_types,
    }
    return render(request, 'create_reservation.html', context)


def homepage(request):
    hotels = Hotel.objects.all()
    return render(request, 'homepage.html', {'hotels': hotels})

def hotel_detail(request, hotel_id):
    hotel = get_object_or_404(Hotel, pk=hotel_id)
    return render(request, 'hotel_detail.html', {'hotel': hotel})

def reservation_success(request):
    name = request.GET.get('name')
    phone = request.GET.get('phone')
    email = request.GET.get('email')
    hotel_id = request.GET.get('hotel')
    room_type_id = request.GET.get('room')
    check_in_date = request.GET.get('check_in_date')
    check_out_date = request.GET.get('check_out_date')

    
    # Get the selected hotel and room type objects
    hotel = Hotel.objects.get(pk=hotel_id)
    room_type = RoomType.objects.get(pk=room_type_id)

    # Create a reservation object
    reservation = Reservation(
        name=name,
        phone=phone,
        email=email,
        hotel=hotel,
        room=room_type,
        check_in_date=check_in_date,
        check_out_date=check_out_date
    )
    reservation.save()

    res = get_object_or_404(Reservation, name=name)
    res_id = res.id


    return render(request, 'reservation_success.html', {'reservation': reservation, 'res_id': res_id})

zomato/templates/create_reservation.html
{% load static %}

<!-- create_reservation.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Reservation</title>
    <link rel="stylesheet" type="text/css" href="{% static 'reservation.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 600px;
            margin-top: 20px;
            margin: 50px auto;
            background: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #333;
        }

        form {
            margin-top: 20px;
        }

        label {
            font-weight: bold;
            color: #555;
        }

        input[type="text"],
        input[type="tel"],
        input[type="email"],
        select,
        input[type="date"],
        button {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 3px;
            box-sizing: border-box;
        }

        button {
            background-color: #007bff;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }

        .home-button {
            text-decoration: none;
            color: #007bff;
            display: block;
            text-align: center;
            margin-bottom: 20px;
        }

        .home-button h1 {
            border: 2px solid #007bff;
            border-radius: 3px;
            padding: 10px;
            margin: 0;
        }

        .home-button {
    text-decoration: none;
    color: #007bff;
    display: flex;
    justify-content: center;
    align-items: center;
    margin: 20px;
}

.home-button h1 {
    border: 2px solid #007bff;
    border-radius: 3px;
    padding: 10px;
    margin: 0;
}


    </style>
</head>
<body>

    <a href="{% url 'homepage' %}" class="home-button" > <h1 style="border-style: solid; border-radius: 3px; border-color: blue; margin-left: 700px; margin-right: 700px; flex-wrap: wrap;"> HOME </h1> <i class="fas fa-home"></i></a>


    <div class="container"> <!-- Wrap form inside a container -->
        <h1>Create Reservation</h1>
        <form method="GET" action="reservation-success">
            {% csrf_token %}
            <label for="name">Name:</label><br>
            <input type="text" id="name" name="name" required><br>

            <label for="phone">Phone:</label><br>
            <input type="tel" id="phone" name="phone" required><br>

            <label for="email">Email:</label><br>
            <input type="email" id="email" name="email" required><br>

            <label for="hotel">Hotel:</label><br>
            <select id="hotel" name="hotel" required>
                {% for hotel in hotels %}
                <option value="{{ hotel.id }}">{{ hotel.name }}</option>
                {% endfor %}
            </select><br>

            <label for="room">Room Type:</label><br>
            <select id="room" name="room" required>
                {% for room_type in room_types %}
                <option value="{{ room_type.id }}">{{ room_type.type }}</option>
                {% endfor %}
            </select><br>

            <label for="check_in_date">Check-in Date:</label><br>
            <input type="date" id="check_in_date" name="check_in_date" required><br>

            <label for="check_out_date">Check-out Date:</label><br>
            <input type="date" id="check_out_date" name="check_out_date" required><br>

            <button type="submit">Submit</button>
        </form>
    </div> <!-- End of container -->


    

</body>



</html>

zomato/templates/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <link rel="stylesheet" type="text/css" href="{% static 'homepage.css' %}">
    <style>
        .hotel-item img {
            text-align: center;
            width: 200px;
            height: 200px;
            object-fit:cover; /* Preserve aspect ratio */
        }
    </style>
</head>
<body>
    <h1> HOTELS RESERVATION PAGE </h1>
    <div class="hotel-list">
        {% for hotel in hotels %}
          

            <div class="hotel-item">
                <a href="{% url 'hotel_detail' hotel.id %}">
                  <h2 >{{ hotel.name }}</h2>
                  
                    {% if hotel.logo %}
                  <img src = " {{ hotel.logo.url }}" style="display: block;
                  margin: 0 auto; 
                  width: 200px;
                  height: 200px;
                  object-fit: cover;">
                  {% endif %}
                
                </a>
            </div>
        {% endfor %}
    </div>
    <a href="{% url 'create_reservation' %}" class="reservation-btn">Create Reservation</a>
</body>
</html>

zomato/templates/hotel_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel Detail</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hotel_detail.css' %}">
</head>
<body>
    <div class="container">
      <a href="{% url 'homepage' %}" class="home-button" > <h1> HOME </h1> <i class="fas fa-home"></i></a>

        <h1>{{ hotel.name }}</h1>
        <div class="hotel-info">
            <p><strong>Address:</strong> {{ hotel.address }}</p>
            <p><strong>Pool:</strong> {% if hotel.pool %}Yes{% else %}No{% endif %}</p>
            <p><strong>Gym:</strong> {% if hotel.gym %}Yes{% else %}No{% endif %}</p>
            <p><strong>Rating:</strong> {{ hotel.get_rating_display }}</p>
        </div>
        <div class="room-types">
            <h2>Room Types</h2>
            <ul>
                {% for room_type in hotel.roomtypes.all %}
                    <li>{{ room_type.type }} - {{ room_type.description }}</li>
                {% endfor %}
            </ul>
        </div>
        <a href="{% url 'create_reservation' %}" class="reservation-btn">Create Reservation</a>

    </div>
</body>
</html>

zomato/templates/reservation_success.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reservation Success</title>
    <link rel="stylesheet" href="{% static 'reservation_success.css' %}">
    
</head>
<body>

    <a href="{% url 'homepage' %}" class="home-button" > <p style="border-radius: 3px; border-color: whitesmoke; padding-left: 700px; padding-right: 700px; flex-wrap: wrap; border-style: none; font-size: 40px;"> H O M E </p> <i class="fas fa-home"></i></a>


    <h1>Reservation Successful</h1>
    
    <p>ID: {{ res_id }}</p>

    <p>Name: {{ reservation.name }}</p>
    <p>Phone: {{ reservation.phone }}</p>
    <p>Email: {{ reservation.email }}</p>
    <p>Hotel: {{ reservation.hotel }}</p>
    <p>Room: {{ reservation.room}}</p>
    <p>Check-in Date: {{ reservation.check_in_date }}</p>
    <p>Check-out Date: {{ reservation.check_out_date }}</p>
</body>
</html>